### PR TITLE
Add Gelf Http transport

### PR DESCRIPTION
**Pull request by mantasaudickas**
I was not able to build xproj solution as I have newer version installed. For .NET additional reference were needed: System.Net.Http.
For .NET Core there are needed System.Net.Http and System.Net.Http.Headers.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/whir1/serilog-sinks-graylog/pull/7" target="_blank">ReviewNinja

**Comment by whir1** [comment]
I can't accept your pr because build failed and this code without tests.

PS I'm trying migrate project to new csproj files to work with it. But it's very bugged =(

**Comment by mantasaudickas** [comment]
Well, build fails because of new csproj files, probably I cannot modify build process :)
And yes, I agree about tests, just had no time to write them.
Basically I can also make separate nuget package just for transport configuration.

**Comment by whir1** [comment]
I'll add new project files worked with ws2017 in branch 
https://github.com/whir1/serilog-sinks-graylog/tree/Vs2017

it's work, but now i should edit appveyor build =\

**Pull request closed without merging**
